# Generated by Django 2.0.1 on 2018-05-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haircut', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=180, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=180, null=True)),
                ('barber_name', models.CharField(blank=True, max_length=180, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
